[package]
name = "ecs_basics"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bevy.workspace = true
ron.workspace = true
serde.workspace = true

[[bin]]
name = "entity"
path = "src/bin/05_entity.rs"

[[bin]]
name = "component"
path = "src/bin/06_component.rs"

[[bin]]
name = "system"
path = "src/bin/07_system.rs"

[[bin]]
name = "query"
path = "src/bin/08_query.rs"

[[bin]]
name = "resource"
path = "src/bin/09_resource.rs"

[[bin]]
name = "commands"
path = "src/bin/10_commands.rs"

[[bin]]
name = "entity_lifecycle"
path = "src/bin/10a_entity_lifecycle.rs"

[[bin]]
name = "messages"
path = "src/bin/11_messages.rs"

[[bin]]
name = "states"
path = "src/bin/12_states.rs"

[[bin]]
name = "asset_loading"
path = "src/bin/12a_asset_loading.rs"

[[bin]]
name = "dynamic_world"
path = "src/bin/12b_dynamic_world.rs"

[[bin]]
name = "dynamic_world_solution"
path = "src/bin/dynamic_world_solution.rs"

[[bin]]
name = "save_game_model"
path = "src/bin/12c_save_game_model.rs"

[[bin]]
name = "behavior_abstraction"
path = "src/bin/12d_behavior_abstraction.rs"

[[bin]]
name = "input_actions"
path = "src/bin/12e_input_actions.rs"

[[bin]]
name = "fixed_update"
path = "src/bin/12f_fixed_update.rs"

[[bin]]
name = "ecs_testing"
path = "src/bin/12g_ecs_testing.rs"
